name: CC Contracts Blob upload

on:
  workflow_dispatch:
    inputs:     
      ENVIRONMENT:
        type: choice
        description: 'Environment'
        options:
          - dev
          - qa 
      USE_VERSION:
        type: string
        description: Define a tag version that you want to upload  
        required: true
        default: latest

concurrency:
  group: cc-contracts-upload-${{ github.head_ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  upload-contracts:
    name: Upload contracts to blob storage
    runs-on: ubuntu-latest
    steps:

    - name: Download Contracts from Release Artifacts (Specific Tag)
      uses: robinraju/release-downloader@v1.9
      id: download-contracts
      if: inputs.USE_VERSION != 'latest'
      with:
        fileName: Contracts.zip
        tag: '${{ inputs.USE_VERSION }}-contracts'
        out-file-path: ${{ github.workspace }}
        
    - name: Download Contracts from Release Artifacts (Latest)
      uses: robinraju/release-downloader@v1.9
      id: download-contracts-latest
      if: inputs.USE_VERSION == 'latest'
      with:
        fileName: Contracts.zip
        latest: true
        out-file-path: ${{ github.workspace }}

    - name: Define Subscription
      id: azure-subscription
      run: |
        if [ ${{ inputs.Environment }} = "dev" ]; then
          echo "id=${{ secrets.AZURE_SUBSCRIPTION_ID_DEV  }}" >> $GITHUB_OUTPUT
          echo "Using DEV subscription"
        elif [ ${{ inputs.Environment }} = "qa" ]; then
          echo "id=${{ secrets.AZURE_SUBSCRIPTION_ID_QA  }}" >> $GITHUB_OUTPUT
          echo "Using QA subscription"
        else
          echo "::warning::The functionAppSuffix input is not recognized. Expected 'dev' or 'qa', but got ${{ inputs.Environment }}."
          exit 1
        fi

    - name: Define Variables
      id: vars
      run: |
        if [ ${{ inputs.Environment }} = "dev" ]; then
          echo "AZURE_STORAGE_ACCOUNT_NAME=${{ vars.AZURE_STORAGE_ACCOUNT_NAME_DEV  }}" >> $GITHUB_OUTPUT
          echo "AZURE_STORAGE_CONTAINER_NAME=${{ vars.AZURE_STORAGE_CONTAINER_NAME_DEV  }}" >> $GITHUB_OUTPUT
        elif [ ${{ inputs.Environment }} = "qa" ]; then
          echo "AZURE_STORAGE_ACCOUNT_NAME=${{ vars.AZURE_STORAGE_ACCOUNT_NAME_QA  }}" >> $GITHUB_OUTPUT
          echo "AZURE_STORAGE_CONTAINER_NAME=${{ vars.AZURE_STORAGE_CONTAINER_NAME_QA  }}" >> $GITHUB_OUTPUT
        else
          echo "::warning::The functionAppSuffix input is not recognized. Expected 'dev' or 'qa', but got ${{ inputs.Environment }}."
          exit 1
        fi

    - name: Login via Azure CLI
      uses: azure/login@v2
      with:
        creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_AD_CLIENT_SECRET }}","subscriptionId":"${{ steps.azure-subscription.outputs.id }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'


    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az storage blob upload --account-name ${{ steps.vars.outputs.AZURE_STORAGE_ACCOUNT_NAME }} --container-name ${{ steps.vars.outputs.AZURE_STORAGE_CONTAINER_NAME }} --validate-content --file Contracts.zip --name "contracts/${{steps.download-contracts-latest.outputs.release_name || steps.download-contracts.outputs.release_name}}.zip" --overwrite
      